# .readthedocs.yml
# Read the Docs configuration file

# Details
# - https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
      - method: pip
        path: .
        extra_requirements:
          - docs

sphinx:
  configuration: docs/source/conf.py

  # Use standard HTML builder.
  builder: html

  # Fail on all warnings to avoid broken references.
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf
