name: "Tests"

on:
  push:
    branches: [ main ]
  pull_request: ~
  workflow_dispatch:

# Cancel redundant in-progress jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-full:
    name: "Full: Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          "ubuntu-latest",
          "macos-latest",
          "windows-latest",
        ]
        python-version: [
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "pypy3.10",
        ]
    env:
      UV_SYSTEM_PYTHON: true

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: ${{ matrix.python-version }}
        cache-dependency-glob: |
          pyproject.toml

    - name: Install and validate package
      run: |
        uv pip install '.[full,develop,test]'
        poe check


  test-minimal:
    name: "Minimal: Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.13"]
    env:
      UV_SYSTEM_PYTHON: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: ${{ matrix.python-version }}
        cache-dependency-glob: |
          pyproject.toml

    - name: Install and validate package
      run: |
        uv pip install '.[develop,test]'
        poe check
